# docker-compose.yml for urbalurba database running in docker.
# is built in github using github actions and pushed to ghcr.io 
# NB on the host the postgresql port 5435 must be free

version: '3.8'

services:
  urbalurba_db:
    container_name: urbalurba_db
    image: ghcr.io/terchris/urbalurba-db:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=Smartbygutta01
    ports:
      - "5435:5432"
    volumes:
      - urbalurba-db-volume:/var/lib/postgresql/data
    networks:
      - urbalurba-network


volumes:
  urbalurba-db-volume:
    name: urbalurba-db-volume
    driver: local

networks:
  urbalurba-network:
    name: urbalurba-network
    driver: bridge
