# docker-compose.yml for urbalurba database running in docker
version: '3.8'
services:
  urbalurba-db:
    container_name: urbalurba-db
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_PORT=${DATABASE_PORT}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - urbalurba-db-volume:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    command: postgres -c 'listen_addresses=*' -p ${DATABASE_PORT}
    networks:
      - urbalurba-network

volumes:
  urbalurba-db-volume:
    name: urbalurba-db
    driver: local

networks:
  urbalurba-network:
    name: urbalurba-network
    driver: bridge
